const path=require('path');const http=require('http');const express=require('express');const {Server}=require('socket.io');
const app=express(),server=http.createServer(app),io=new Server(server),PORT=process.env.PORT||3000;app.use(express.static(path.join(__dirname,'public')));
const rooms=new Map(),MAX=6,MIN=2,DICE=5;
const roll=n=>Array.from({length:n},()=>1+Math.floor(Math.random()*6));
const alive=r=>r.players.filter(p=>p.dice.length);const total=r=>r.players.reduce((n,p)=>n+p.dice.length,0);const count=(r,f)=>r.players.reduce((n,p)=>n+p.dice.filter(d=>d===f).length,0);
function code(){let c;do c=Array.from({length:5},()=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*32)]).join('');while(rooms.has(c));return c}
function higher(a,b){return !b||a.quantity>b.quantity||(a.quantity===b.quantity&&a.face>b.face)}
function next(r,id){let a=alive(r),i=a.findIndex(p=>p.id===id);return a[(i+1)%a.length]}
function state(r){return {code:r.code,phase:r.phase,players:r.players.map(p=>({id:p.id,name:p.name,diceCount:p.dice.length,connected:p.connected})),currentPlayerId:r.currentPlayerId,bid:r.bid,reveal:r.reveal,message:r.message,winner:r.winner}}
function send(r){io.to(r.code).emit('state',state(r));r.players.forEach(p=>io.to(p.id).emit('privateDice',{dice:p.dice}))}
function round(r,id){r.players.forEach(p=>{if(p.dice.length)p.dice=roll(p.dice.length)});r.phase='playing';r.bid=null;r.reveal=null;r.currentPlayerId=id;let p=r.players.find(x=>x.id===id);r.message=`${p.name}'s turn.`;send(r)}
function winner(r){let a=alive(r);if(a.length===1){r.phase='gameOver';r.winner=a[0].name;r.currentPlayerId=null;r.message=`${a[0].name} wins the game!`;return true}return false}
io.on('connection',s=>{
s.on('createRoom',({name})=>{name=String(name||'').trim().slice(0,20);if(!name)return s.emit('errorMessage','Enter a name.');let r={code:code(),phase:'lobby',players:[{id:s.id,name,dice:[],connected:true}],currentPlayerId:null,bid:null,reveal:null,message:'Waiting for players...',winner:null};rooms.set(r.code,r);s.join(r.code);s.data.roomCode=r.code;send(r)});
s.on('joinRoom',({code:rc,name})=>{rc=String(rc||'').trim().toUpperCase();name=String(name||'').trim().slice(0,20);let r=rooms.get(rc);if(!name)return s.emit('errorMessage','Enter a name.');if(!r)return s.emit('errorMessage','Room not found.');if(r.phase!=='lobby')return s.emit('errorMessage','Game already started.');if(r.players.length>=MAX)return s.emit('errorMessage','Room is full.');r.players.push({id:s.id,name,dice:[],connected:true});s.join(rc);s.data.roomCode=rc;r.message=`${name} joined the room.`;send(r)});
s.on('startGame',()=>{let r=rooms.get(s.data.roomCode);if(!r)return;if(r.players[0].id!==s.id)return s.emit('errorMessage','Only the host can start.');if(r.players.length<MIN)return s.emit('errorMessage','Need at least 2 players.');r.players.forEach(p=>p.dice=roll(DICE));r.phase='playing';r.currentPlayerId=r.players[0].id;r.bid=null;r.reveal=null;r.message=`${r.players[0].name}'s turn.`;send(r)});
s.on('bid',({quantity,face})=>{let r=rooms.get(s.data.roomCode);if(!r||r.phase!=='playing')return;if(r.currentPlayerId!==s.id)return s.emit('errorMessage','It is not your turn.');quantity=Number(quantity);face=Number(face);let b={quantity,face,playerId:s.id};if(!Number.isInteger(quantity)||!Number.isInteger(face)||face<1||face>6||quantity<1||quantity>total(r)||!higher(b,r.bid))return s.emit('errorMessage','Invalid or too-low bid.');r.bid=b;let n=next(r,s.id);r.currentPlayerId=n.id;r.message=`${n.name}'s turn.`;send(r)});
s.on('callLiar',()=>{let r=rooms.get(s.data.roomCode);if(!r||r.phase!=='playing')return;if(r.currentPlayerId!==s.id)return s.emit('errorMessage','It is not your turn.');if(!r.bid)return s.emit('errorMessage','There is no bid to challenge.');let caller=r.players.find(p=>p.id===s.id),bidder=r.players.find(p=>p.id===r.bid.playerId),actual=count(r,r.bid.face),truth=actual>=r.bid.quantity,loser=truth?caller:bidder;loser.dice.pop();r.reveal={caller:caller.name,bidder:bidder.name,quantity:r.bid.quantity,face:r.bid.face,actualCount:actual,bidWasTrue:truth,loser:loser.name,loserId:loser.id};r.phase='reveal';r.currentPlayerId=null;r.message=truth?`The bid was TRUE! ${caller.name} loses a die.`:`LIAR! ${bidder.name} loses a die.`;if(winner(r)){send(r);return}send(r)});
s.on('continueRound',()=>{let r=rooms.get(s.data.roomCode);if(!r||r.phase!=='reveal'||!r.reveal)return;round(r,r.reveal.loserId)});
s.on('restartGame',()=>{let r=rooms.get(s.data.roomCode);if(!r||r.players[0].id!==s.id)return;r.players.forEach(p=>p.dice=roll(DICE));r.phase='playing';r.bid=null;r.reveal=null;r.winner=null;r.currentPlayerId=r.players[0].id;r.message=`${r.players[0].name}'s turn.`;send(r)});
s.on('disconnect',()=>{let r=rooms.get(s.data.roomCode);if(!r)return;let p=r.players.find(x=>x.id===s.id);if(!p)return;p.connected=false;if(r.phase==='lobby'){r.players=r.players.filter(x=>x.id!==s.id);if(!r.players.length)rooms.delete(r.code)}send(r)})});
server.listen(PORT,()=>console.log(`Liar's Dice server running on http://localhost:${PORT}`));
